// <auto-generated/>
using ImGuiNative;
namespace ImGui;

public unsafe struct ImGuiIOManaged
{
	public ImGuiIO* NativePtr { get; }

	public ImGuiIOManaged(ImGuiIO* nativePtr)
	{
		NativePtr = nativePtr;
	}

	public ImGuiIOManaged(IntPtr nativePtr)
	{
		NativePtr = (ImGuiIO*)nativePtr;
	}

}
