name: Build natives

on:
  workflow_dispatch:
# push:
#   branches: [ "master" ]
# pull_request:
#   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dear_bindings.Dockerfile --tag dear_bindings:v1
    - name: Run Docker image
      run: |
        docker run --rm -i -v "${GITHUB_WORKSPACE}/cimgui:/cimgui_build" dear_bindings:v1
    - name: Verify compilation
      run: |
        file ${{ github.workspace }}/cimgui/cimgui.dll
        file ${{ github.workspace }}/cimgui/cimgui.so
        file ${{ github.workspace }}/cimgui/cimgui.dylib

    - name: upload-artifacts-win-x64
      uses: actions/upload-artifact@v4.3.1
      with: 
        name: cimgui.dll
        path: ${{ github.workspace }}/cimgui/cimgui.dll

    - name: upload-artifacts-linux-x64
      uses: actions/upload-artifact@v4.3.1
      with: 
        name: cimgui.so
        path: ${{ github.workspace }}/cimgui/cimgui.so

    - name: upload-artifacts-osx-arm64
      uses: actions/upload-artifact@v4.3.1
      with: 
        name: cimgui.dylib
        path: ${{ github.workspace }}/cimgui/cimgui.dylib
