name: Docker Image CI

on:
  workflow_dispatch:
# push:
#   branches: [ "master" ]
# pull_request:
#   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dear_bindings.Dockerfile --tag dear_bindings:v1
    - name: Run Docker image
      run: |
        scriptPath="`dirname \"$0\"`"
        docker --rm -i -v "${scriptPath}/cimgui:/cimgui_build" dear_bindings:v1
    - name: Verify compilation
      run: |
        file cimgui/cimgui.dll
        file cimgui/cimgui.so
        file cimgui/cimgui.dylib
    - name: upload-artifacts
      uses: actions/upload-artifact@v4.3.1
      with: 
        name: cimgui
        path: cimgui/*
